remote_theme: b2a3e8/jekyll-theme-console
title: "arabel1a's landing page"
description: "A CNC ML kiddie"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

# footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
