remote_theme: arabel1a/jekyll-theme-console

title: "arabel1a's landing page"

header_pages:
  - index.md
  - about.md

style: dark

footer: 'contact via tg <a href="https://t.me/arabel1a">@arabel1a</a>'

# Build settings
markdown: kramdown
