remote_theme: arabel1a/jekyll-theme-console

title: Misha Shirokikh's homepage

plugins:
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md

style: dark

footer: 'contact via tg <a href="https://t.me/arabel1a">@arabel1a</a>'

