remote_theme: hemangsk/DevJournal
title: "arabel1a's landing page"
description: "A CNC ML kiddie"

header_pages:
  - index.md
  - peter.md
  - about.md

style: dark

footer: 'contact via tg <a href="https://t.me/arabel1a">@arabel1a</a>'

# Build settings
markdown: kramdown
